### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by honyczek** [myjamtv/kodi#1]
When I try to open My Jam TV plugin in Kodi, it throws an error. This is description from the log:

```
2021-05-26 08:20:53.801 T:1936735664   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-05-26 08:20:55.646 T:1791980416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.myjamtv/addon.py", line 22, in <module>
                                                url = urllib2.urlopen("http://myjamtv.com/stream_url.txt").readline().strip()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
2021-05-26 08:20:55.661 T:1571799936   ERROR: GetDirectory - Error getting plugin://plugin.video.myjamtv/
2021-05-26 08:20:55.663 T:1936735664   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.myjamtv/) failed

```

**Comment by ejm** [comment]
My Jam TV and it's successor, IndieCast TV, have both closed their live channels. Sorry for the inconvenience.
